name: Update Blocklist
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - 'README.md'
  schedule:
    - cron: '0 14 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y pcregrep
          chmod +x ./generator.sh
          ./generator.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "blocklist"
          git push
